title: exs
email: 
description: >
  A log of daily programming chrestomathy and other exercise
baseurl: "/exs"
url: "http://bitfragment.net"
twitter_username: bitfragmented
github_username:  bitfragment

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1

defaults:
  -
    scope:
      path: "" # all files
      type: "posts"
    values:
      layout: post
